# Elixir CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-elixir/ for more details
# checksum pinning? https://binarynoggin.com/deploying-phoenix-with-circleci/?utm_campaign=elixir_radar_226&utm_medium=email&utm_source=RD+Station 
version: 2.1
jobs:
  test:
    docker:
      - image: modaltonn/debian-elixir:latest

    working_directory: ~/repo
    steps:
      - checkout

      - run: mix local.hex --force
      - run: mix local.rebar --force
      - run: mix deps.get
  deploy:
    docker:
      - image: modaltonn/debian-elixir:latest
    working_directory: ~/repo
    steps:
      - add_ssh_keys:
          fingerprints:
            - "ae:39:28:e5:90:76:56:f1:9b:46:34:8c:ed:85:ba:8f"
      - checkout
      - run: mix local.hex --force
      - run: mix local.rebar --force
      - run: mix deps.get
      - run: MIX_ENV=prod mix release
      - run: tar -zcvf homecooked-prod-temp.tar -C _build/prod/rel/homecooked .

      - run:
          name: Upload release
          command: |
            scp -o "StrictHostKeyChecking no" homecooked-prod-temp.tar \
            admin@$EC2_DOMAIN_NAME:~/

      - run:
          name: Untar release
          command: |
            ssh admin@$EC2_DOMAIN_NAME \
            "mkdir homecooked-prod-temp && tar xf homecooked-prod-temp.tar -C homecooked-prod-temp"

      - run:
          name: Stop running instance
          command: |
             ssh admin@$EC2_DOMAIN_NAME \
             "sudo kill $$(sudo ~/homecooked-prod/bin/homecooked pid)"

      - run:
          name: Migrate DB
          command: |
             ssh admin@$EC2_DOMAIN_NAME \
             "sudo ~/homecooked-prod-temp/bin/homecooked eval "Homecooked.Release.migrate""

      - run:
          name: Replace directory
          command: |
             ssh admin@$EC2_DOMAIN_NAME \
             "sudo rm -rf ~/homecooked-prod && mv ~/homecooked-prod-temp ~/homecooked-prod && rm homecooked-prod-temp.tar"

      - run:
          name: Start new instance
          command: |
             ssh admin@$EC2_DOMAIN_NAME \
             "bash --login -c \"sudo ~/homecooked-prod/bin/homecooked daemon\""

      - run:
          name: Check the new instance is running
          command: |
            ssh admin@$EC2_DOMAIN_NAME \
            "sudo ~/homecooked-prod/bin/homecooked pid"

workflows:
  version: 2
  build_and_deploy:
    jobs:
      - test
      - deploy:
          requires:
            - test
